Numpy - Array: Introduction.

In [ ]:
import numpy as np
# initialize an all zero array with size 2 X 3
zeros_arr = np . zeros ((2 ,3) )
print (" A zeros array is \n", zeros_arr , " with dimensions ", zeros_arr . shape , "\n")


 A zeros array is 
 [[0. 0. 0.]
 [0. 0. 0.]]  with dimensions  (2, 3) 



Numpy - Array: Type.

In [ ]:
import numpy as np

# Create and display zero, one, and n-dimensional arrays
zero_dim_array = np.array(5)
one_dim_array = np.array([1, 2, 3])
n_dim_array = np.array([[1, 2], [3, 4]])

for arr in [zero_dim_array, one_dim_array, n_dim_array]:
    print(f"Array:\n{arr}\nDimension: {arr.ndim}\nData type: {arr.dtype}\n")


Array:
5
Dimension: 0
Data type: int64

Array:
[1 2 3]
Dimension: 1
Data type: int64

Array:
[[1 2]
 [3 4]]
Dimension: 2
Data type: int64



Array Dimensions: Shape

In [ ]:
import numpy as np
# Create arrays of different dimensions
array_0d = np . array (5)
array_1d = np . array ([1 , 2 , 3 , 4 , 5])
array_2d = np . array ([[1 , 2 , 3] , [4 , 5 , 6]])
array_3d = np . array ([[[1 , 2] , [3 , 4]] , [[5 , 6] , [7 , 8]]])
# Print arrays with shapes
for i , arr in enumerate ([ array_0d , array_1d , array_2d , array_3d ]) :
  print ( f"{i}D Array :\n{arr }\nShape : {arr. shape }\n")

0D Array :
5
Shape : ()

1D Array :
[1 2 3 4 5]
Shape : (5,)

2D Array :
[[1 2 3]
 [4 5 6]]
Shape : (2, 3)

3D Array :
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape : (2, 2, 2)



Array Dimensions: reshape.

In [ ]:
import numpy as np

array = np.array([[1, 2, 3], [4, 5, 6]])  # Shape (2, 3)
reshaped_array = array.reshape(3, 2)      # Reshape to (3, 2), keeping 6 elements

print("Original Shape:", array.shape, "\nReshaped Shape:", reshaped_array.shape)


Original Shape: (2, 3) 
Reshaped Shape: (3, 2)


 How to create an Array?

In [ ]:
import numpy as np

a = np.arange(1, 10)
print(a)

x = range(1, 10)
print(x)     # x is an iterator
print(list(x))

# further arange examples :
x = np.arange(10.4)
print(x)

x = np.arange(0.5, 10.4, 0.8)
print(x)


[1 2 3 4 5 6 7 8 9]
range(1, 10)
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0.5  1.3  2.1  2.9  3.7  4.5  5.3  6.1  6.9  7.7  8.5  9.3 10.1]


In [ ]:
import numpy as np

# 50 values between 1 and 10:
print(np.linspace(1, 10))

# 7 values between 1 and 10:
print(np.linspace(1, 10, 7))

# excluding the endpoint:
print(np.linspace(1, 10, 7, endpoint=False))


[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
[ 1.   2.5  4.   5.5  7.   8.5 10. ]
[1.         2.28571429 3.57142857 4.85714286 6.14285714 7.42857143
 8.71428571]


 How to create an Array?


In [ ]:
import numpy as np
# Create arrays of specified shapes
ones_array = np . ones ((2 , 3) ) # Shape : (2 , 3)
zeros_array = np . zeros ((3 , 2) ) # Shape : (3 , 2)
empty_array = np . empty ((2 , 2) ) # Shape : (2 , 2)
identity_matrix = np . eye (3) # Shape : (3 , 3)
print ( ones_array , zeros_array , empty_array ,identity_matrix , sep ='\n\n')

[[1. 1. 1.]
 [1. 1. 1.]]

[[0. 0.]
 [0. 0.]
 [0. 0.]]

[[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np
array_from_list = np . array ([1 , 2 , 3]) # [1 2 3]
array_from_tuple = np . array ((4 , 5 , 6) ) # [4 5 6]
array_from_nested_list = np . array ([[1 , 2 , 3] , [4 , 5 , 6]]) # [[1 2 3] [4 5 6]]
print ( array_from_list , array_from_tuple , array_from_nested_list , sep ='\n')

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
array_from_list = np . array ([1 , 2 , 3]) # [1 2 3]
array_from_tuple = np . array ((4 , 5 , 6) ) # [4 5 6]
array_from_nested_list = np . array ([[1 , 2 , 3] , [4 , 5 , 6]]) # [[1 2 3] [4 5 6]]
print ( array_from_list , array_from_tuple , array_from_nested_list , sep ='\n')

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
array = np . array ([1 , 2 , 3])
# Multiplies each element by 2 , result : [2 , 4 , 6]
new_array = array * 2
# Creates a new array with the same elements
copied_array = np . copy ( array )
# Slices elements from index 1 to 3 , result :[2]
sliced_array = array [1:2]

In [ ]:
import numpy as np
arr1 = np . array ([[1 , 2] , [3 , 4]]) # Shape : (2 , 2)
arr2 = np . array ([[5 , 6] , [7 , 8]]) # Shape : (2 , 2)
# Stacking examples
hstacked = np . hstack (( arr1 , arr2 ) )
# Output hstack : [[1 2 5 6] [3 4 7 8]]
vstacked = np . vstack (( arr1 , arr2 ) )
# Output vstack [[1 2] [3 4] [5 6] [7 8]]
colstacked = np . column_stack (( arr1 [0] , arr2 [0]) )
# Output column stack : [[1 5] [2 6]]
print ( hstacked , vstacked , colstacked , sep ='\n')

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 5]
 [2 6]]


In [ ]:
import numpy as np
arr1 = np . array ([[1 , 2] , [3 , 4]]) # Shape : (2 , 2)
arr2 = np . array ([[5 , 6] , [7 , 8]]) # Shape : (2 , 2)
concat_axis0 = np . concatenate (( arr1 , arr2 ) , axis =0)
# Concatenate along axis 0 ( vertical ) Shape : (4 , 2)
concat_axis1 = np . concatenate (( arr1 , arr2 ) , axis =1)
# Concatenate along axis 1 ( horizontal ) Shape : (2 , 4)
print ( concat_axis0 , concat_axis1 , sep ='\n')


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


Getting Started with Numpy.
3. Indexing and Slicing.


Code Example: Slicing and Indexing.

In [ ]:
import numpy as np
# Arrays
arr1d = np . array ([0 , 1 , 2 , 3 , 4 , 5])
arr2d = np . array ([[0 , 1 , 2] , [3 , 4 , 5] , [6 , 7 , 8]])
arr3d = np . array ([[[0 , 1] , [2 , 3]] , [[4 , 5] , [6 , 7]] , [[8 ,9] , [10 , 11]]])
# Slicing examples
print (" Basic :", arr1d [1:4] , arr2d [1:3 , 0:2] , arr3d [1:2 , 0:2 ,1:2])
# Output Basic : arr1d :[1 2 3] arr2d :[[3 4] [6 7]] arr3d:[[[5] [7]]]
print (" Step :", arr1d [1:5:2] , arr2d [::2 , 1::2] , arr3d [::2 ,::2 , 1::2])
 # Output : Step : [1 3] [[1] [7]] [[[1] [9]]]

 Basic : [1 2 3] [[3 4]
 [6 7]] [[[5]
  [7]]]
 Step : [1 3] [[1]
 [7]] [[[1]]

 [[9]]]
